### ISSUE TITLE
Testing string empty raises exception

### ISSUE THREAD

**Issue by sebukoleth** [json-path/JsonPath#371]
JSON:
{
 "messageSourceID": "meta-service",
 "payloadSize": "1024",
 "messageID" : "<uid>",
 "messageProperties" : {
       "typeId"     : 7,
       "typeName"   : "Task",
       "uoid"       : "12345",
       "name"       : "SrcConn",
       "ownerId"    : "",
       "action"     : "CREATE"
   }
}

Filter expression:
$.messageProperties[?(@.action empty)]

Exception raised:
Exception in thread "main" com.jayway.jsonpath.InvalidPathException: Expected character: )
	at com.jayway.jsonpath.internal.CharacterIndex.readSignificantChar(CharacterIndex.java:203)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalANDOperand(FilterCompiler.java:170)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalAND(FilterCompiler.java:149)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalOR(FilterCompiler.java:129)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:75)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:53)
	at com.jayway.jsonpath.internal.path.PathCompiler.readFilterToken(PathCompiler.java:456)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:135)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:231)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:165)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:139)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:118)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:54)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:69)
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:149)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:488)

**Comment by jochenberger** [comment]
If I'm not mistaken, you should use `$.messageProperties[?(@.action empty true)]` (or `$.messageProperties[?(@.action empty false)]`, respectively).

**Comment by sebukoleth** [comment]
You are absolutely right. My bad.
