### ISSUE TITLE
JSONPath compilation fails if a path with filter expression is used as an argument to a function

### ISSUE THREAD

**Issue by dmitryarmolovich** [json-path/JsonPath#399]
When a path with a filter expression is used as an argument to a function, such JSONPath cannot be compiled because of the issue in the function arguments parser. It happens because the function arguments are parsing incorrectly.

**Try to compile the following expression:**
`$.concat($.address_components[?(@.types[0] == 'premise')].long_name, "-", $.address_components[?(@.types[0] == 'country')].long_name)`

**Compiler uses the following strings as an arguments of the concat function:**
arg1= `$.address_components[?(@.types[0] == 'premise'))].long_name`
arg2= `-`
arg3= `$.address_components[?(@.types[0] == 'country'))].long_name`

**Expected result:**
Expression successfully compiled.

**Actual result:**
```
com.jayway.jsonpath.InvalidPathException: Could not parse token starting at position 20. Expected ?, ', 0-9, * 
	at com.jayway.jsonpath.internal.path.PathCompiler.fail(PathCompiler.java:616) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:143) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:237) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:151) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:171) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.parseFunctionParameters(PathCompiler.java:356) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:217) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:151) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:171) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75) ~[json-path-2.4.0.jar:2.4.0]
```

**Comment by haruntuncay** [comment]
Hello @kallestenflo, are you guys open to contributions ? I would like to help implement some of the futures requested.

**Comment by zengmmm00** [comment]
Hi! I would like to work on this feature.

**Comment by aosynsky** [comment]
Fixed with #620
