### ISSUE TITLE
Stackoverflow for [] notation with unclosed attribute

### ISSUE THREAD

**Issue by maryoush** [json-path/JsonPath#428]
Hi
Environment 
MacOS
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
Java 
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

JsonPath version : 2.4.0, 2.3.0, 2.2.0,2.1.0
`<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<version>${json-path.version}</version>
			<scope>compile</scope>
		</dependency>
`

For given expression 

`@Test
	public void stackOverflow()
	{
		JsonPath.compile("$['boo','foo][?(@ =~ /bar/)]");
	}
`

I get 
`java.lang.StackOverflowError
	at java.io.StringWriter.<init>(StringWriter.java:65)
	at com.jayway.jsonpath.internal.Utils.unescape(Utils.java:177)
	at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:590)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:237)
	
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:151)
	at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)
	at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:237)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:151)
	at com.jayway.jsonpath.internal.path.PathCompiler.readBracketPropertyToken(PathCompiler.java:612)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:138)

...
Process finished with exit code 255
`

**Comment by KowalczykBartek** [comment]
Hi JsonPath team,
i have some initial proposition for fix https://github.com/json-path/JsonPath/pull/430 ,
more details in description.
