### ISSUE TITLE
Issue setting values from / to JSON Objects?

### ISSUE THREAD

**Issue by michelbetancourt** [json-path/JsonPath#432]
Hello, it seems that this implementation of JsonPath works pretty well when setting the first level of keys of an object (from existing to new instance).. eg

if we set values this way (with the specific options set in "jsonConfig" below):

 ```java
Configuration jsonConfig = Configuration.builder()
            .options(DEFAULT_PATH_LEAF_TO_NULL, SUPPRESS_EXCEPTIONS)
            .build();
Map<String, Object> newObject = new LinkedHashMap<>();
DocumentContext reader = JsonPath.parse(data, jsonConfig);
DocumentContext writer = JsonPath.parse(newObject, jsonConfig);

JsonPath fromPath = ..
JsonPath toPath = ..
value = reader.read(fromPath);           
writer.set(toPath, value);
```

then this works for all first level keys.. eg
```
$.key1 => $.key
$.car => $.plane
$.house => $.boat
.. and so on
```

but if I'm trying to convert nested paths such as these, it does not work:
```
$.key1 => $.nested.key
$.car => $.nested.plane
$.house => $.nested.boat
.. and so on
```

Is there a better way of doing that that I am overlooking?  Or can this be a bug?

**Comment by jlolling** [comment]
It should work. Could you please provide a test case to illustrate this problem?

**Comment by michelbetancourt** [comment]
Regardless of version (2.2.0 or 2.3.0) this is the result I get with the following test:

```java
@Test
    public void testPathSetting() {
        Configuration jsonConfig = Configuration.builder()
                .options(Option.DEFAULT_PATH_LEAF_TO_NULL, Option.SUPPRESS_EXCEPTIONS)
                .build();
     Map<String, Object> newObject = new LinkedHashMap<>();
     DocumentContext reader = JsonPath.parse(data, jsonConfig);
     DocumentContext writer = JsonPath.parse(newObject, jsonConfig);

     Object value;
     Map<JsonPath, JsonPath> conversionPaths = new LinkedHashMap<>();
     conversionPaths.put(JsonPath.compile("$.key1"), JsonPath.compile("$.key"));
     conversionPaths.put(JsonPath.compile("$.key2"), JsonPath.compile("$.ok"));
     conversionPaths.put(JsonPath.compile("$.key3"), JsonPath.compile("$.nested.key3"));
     for(Map.Entry<JsonPath, JsonPath> path : conversionPaths.entrySet()) {
         JsonPath fromPath = path.getKey();
         JsonPath toPath = path.getValue();
         value = reader.read(fromPath);           
         writer.set(toPath, value);    
     }
     
     assertThat(newObject, hasEntry("key", data.get("key1")));
     assertThat(newObject, hasEntry("ok", data.get("key2")));
     assertThat(newObject, hasKey("nested"));
     Object valOld = JsonPath.read(data, "$.key3");
     Object valNew = JsonPath.read(newObject, "$.nested.key3");
     assertThat(valNew, is(valOld));
    }
```

Obtained result:
```java
java.lang.AssertionError: 
Expected: map containing ["nested"->ANYTHING]
     but: map was [<key=2018-01-25>, <ok=null>]
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.wdpr.cap.accounting.jsonpath.converter.ObjectConverterTest.testPathSetting(ObjectConverterTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)


```

Expected:

JUnit test passes.

**Comment by michelbetancourt** [comment]
Note, if I remove the following option:
```java
Option.DEFAULT_PATH_LEAF_TO_NULL, 
```

Then the result I get is this:
```java
java.lang.AssertionError: 
Expected: map containing ["key"-><2018-01-25>]
     but: map was []
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.wdpr.cap.accounting.jsonpath.converter.ObjectConverterTest.testPathSetting(ObjectConverterTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)


```

Expected:

I would of thought that this option would not have direct impact to the test.  But rather than having key2 as null (which is translated to "ok" key in the new object), then both of these keys should just not be present, is my thought.

**Comment by unjeru** [comment]
If we trying to add something to empty json ("{}") by Json Path like "$.nonexistent.node" we can see an exception

com.jayway.jsonpath.PathNotFoundException: Missing property in path $['nonexistent']

It was cool, if we have some option to create an absent part of json path if it is expected
