### ISSUE TITLE
StringIndexOutOfBoundsException if the query contains single quote. 

### ISSUE THREAD

**Issue by dcreel121** [json-path/JsonPath#460]
Hi, 
I'm using this library to query a JSON string in the following manner: 

1) String data = [  {    "id": "1",    "container": [      "test"    ]  },  {    "id": "2",    "categories": [      "test"    ]  },  {    "id": "3",    "categories": [      "test's"    ]  }]
2) String query = "$[?(@.categories[0] in [test's])]"
3) ReadContext ctx = JsonPath.parse(data);
4) String result = ctx.read(query);

The read query in line 4 results in an StringIndexOutOfBoundsException: 
com.jayway.jsonpath.InvalidPathException: java.lang.StringIndexOutOfBoundsException: length=41; index=41 
at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:64)
at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:149   

This only happens if there's an apostrophe in the query string. I've tried to escape them using \' but that again causes the issue due to the single quote. Is there any way to get around this? I believe the issue may lie in the PathCompiler compile method, but I'm not sure. It gets difficult to debug around there since I don't know the code. Anyways some help would be much appreciated! It would be great to not have to modify the feed before or after the query. Thanks!

**Comment by rjv9645** [comment]
Hello,

The issue you have here seems to be that, in your query, you are not treating what's in the array as a literal. Here's a passing test case using your data:

`	@Test
	public void testRetrieveSingleQoute() {
		String data = "[ { \"id\": \"1\", \"container\": [ \"test\" ] }, { \"id\": \"2\", \"categories\": [ \"test\" ] }, { \"id\": \"3\", \"categories\": [ \"test's\" ] }]";

		String query = "$[?(@.categories[0] in [\"test's\"])]";
		ReadContext ctx = JsonPath.parse(data);
		List result = ctx.read(query, List.class);	
		
		System.out.println(result);
	}`

--Cheers
