### ISSUE TITLE
NullPointerException with JSON containing empty object using deep scanning path using JsonOrgJsonProvider.

### ISSUE THREAD

**Issue by DavidAmmeraal** [json-path/JsonPath#497]
This throws a NullPointerException when I'm using the JsonOrgJsonProvider. Using the default provider and mapper it works fine. 

```java
import com.jayway.jsonpath.Configuration;
import com.jayway.jsonpath.JsonPath;
import com.jayway.jsonpath.spi.json.JsonOrgJsonProvider;
import com.jayway.jsonpath.spi.mapper.JsonOrgMappingProvider;

public class JsonPathThrowsNullPointer {
		
	public static void main(String[] args) {
		String json = "{\"foo\": \"bar\", \"emptyObject\": {}}";

		Configuration config = Configuration.defaultConfiguration()
				.jsonProvider(new JsonOrgJsonProvider())
				.mappingProvider(new JsonOrgMappingProvider());
		
		Object result = JsonPath.using(config).parse(json).read("$..foo");
		System.out.println(result);
	}
	
}
```
Using: 

```xml
<dependency>
  <groupId>com.jayway.jsonpath</groupId>
  <artifactId>json-path</artifactId>
  <version>2.3.0</version>
</dependency>
```

Exception stack trace:

`
Exception in thread "main" java.lang.NullPointerException
	at com.jayway.jsonpath.spi.json.JsonOrgJsonProvider.getPropertyKeys(JsonOrgJsonProvider.java:155)
	at com.jayway.jsonpath.internal.path.ScanPathToken$PropertyPathTokenPredicate.matches(ScanPathToken.java:202)
	at com.jayway.jsonpath.internal.path.ScanPathToken.walkObject(ScanPathToken.java:75)
	at com.jayway.jsonpath.internal.path.ScanPathToken.walk(ScanPathToken.java:41)
	at com.jayway.jsonpath.internal.path.ScanPathToken.walkObject(ScanPathToken.java:84)
	at com.jayway.jsonpath.internal.path.ScanPathToken.walk(ScanPathToken.java:41)
	at com.jayway.jsonpath.internal.path.ScanPathToken.evaluate(ScanPathToken.java:36)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:89)
	at JsonPathThrowsNullPointer.main(JsonPathThrowsNullPointer.java:17)
`

**Comment by kallestenflo** [comment]
Fixed by #699
