### ISSUE TITLE
[BUG] "|" statement is not supported

### ISSUE THREAD

**Issue by eximius313** [json-path/JsonPath#525]
Having such class:
```java
public class Js {
    public static void main(String[] args) {
        String json = "{\n" +
                "    \"foo1\": {\n" +
                "        \"test\":\"bar\",\n" +
                "        \"value\": \"x\"\n" +
                "    },\n" +
                "    \"foo2\": {\n" +
                "        \"test\":\"baz\",\n" +
                "        \"value\": \"y\"\n" +
                "    }\n" +
                "}";

        List<String> values = JsonPath.read(json, "$[?(@.test==\"bar\"|@.test==\"baz\")].value");
        System.out.println(values);
    }
}
```
according to: http://jsonpath.com/ should result:
```
[
  "x",
  "y"
]
```
but it throws
```
Exception in thread "main" com.jayway.jsonpath.InvalidPathException: Expected character: )
	at com.jayway.jsonpath.internal.CharacterIndex.readSignificantChar(CharacterIndex.java:218)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalANDOperand(FilterCompiler.java:185)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalAND(FilterCompiler.java:151)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalOR(FilterCompiler.java:131)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:77)
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:53)
	at com.jayway.jsonpath.internal.path.PathCompiler.readFilterToken(PathCompiler.java:461)
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:141)
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58)
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75)
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:87)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:502)
```

**Comment by eximius313** [comment]
and even if I use `||` it still returns `[]`

**Comment by hf-kklein** [comment]
```json
{
   "foo1" : {
      "test" : "bar",
      "value" : "x"
   },
   "foo2" : {
      "test" : "baz",
      "value" : "y"
   }
}
```
The path `$[?(@.test=="bar"||@.test=="baz")].value` searches for elements on the root level (`$`) fulfilling the condition (`@.test==bar||@.test==baz`). But there is no such element, because the root element only has the keys `"foo1"` and `"foo2"` but not `"test"`. If you sligtly modify your path to search all nested elements recursivly using two dots `..` , it works as intended:
`$..[?(@.test=='bar'||@.test=='baz')].value`
The performance might be worse but the result is the one you expected.

**Comment by eximius313** [comment]
but my query works on http://jsonpath.com/ so clearly it's something wrong with Java library

**Comment by hf-kklein** [comment]
jsonpath.com just uses another implementation of jsonpath than e.g. jsonpath.herokuapp.com . I'm not sure there's actually something like a unified and wellestablished standard besides the very basic operations like accessing keys and indices.

**Comment by kallestenflo** [comment]
I don't think `$[?(@.test==\"bar\"|@.test==\"baz\")].value")` should return any values as explained by @hf-kklein.
