### ISSUE TITLE
Getting java.lang.ClassCastException: class org.json.JSONArray cannot be cast to class java.util.List

### ISSUE THREAD

**Issue by teenaBuchade** [json-path/JsonPath#568]
java.lang.ClassCastException: class org.json.JSONArray cannot be cast to class java.util.List (org.json.JSONArray is in unnamed module of loader 'app'; java.util.List is in module java.base of loader 'bootstrap')

	at com.jayway.jsonpath.internal.filter.ValueNode$JsonNode.asValueListNode(ValueNode.java:341)
	at com.jayway.jsonpath.internal.filter.EvaluatorFactory$ContainsEvaluator.evaluate(EvaluatorFactory.java:220)
	at com.jayway.jsonpath.internal.filter.RelationalExpressionNode.apply(RelationalExpressionNode.java:44)
	at com.jayway.jsonpath.Criteria.apply(Criteria.java:57)
	at com.jayway.jsonpath.Filter$SingleFilter.apply(Filter.java:79)
	at com.jayway.jsonpath.internal.path.PredicatePathToken.accept(PredicatePathToken.java:76)
	at com.jayway.jsonpath.internal.path.PredicatePathToken.evaluate(PredicatePathToken.java:59)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:53)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:61)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:89)

getting above error while using Filter filter1 = Filter.filter(where("tags").contains("tag"));

[
  {
    "user": “test”,
    "tags": ["tag"]
  }
]

which is correct because in ValueNode.java class you are trying to convert jsonArray into list 
return new ValueListNode(Collections.unmodifiableList((List) parse(ctx)));

**Comment by Alanscut** [comment]
hi @teenaBuchade, could you provide your code? I just tested it with v2.4 and it works normal.
Here is my snippet code:
```java
    String json = "[{\n" +
            "\t\"user\": \"test\",\n" +
            "\t\"tags\": [\"tag\"]\n" +
            "}]";

    String filter = Filter.filter(where("tags").contains("tag")).toString();
    System.out.println(filter); // [?(@['tags'] CONTAINS 'tag')]
    DocumentContext context = JsonPath.parse(json);

    Object obj = context.read(filter);
    System.out.println(obj); // [{"user":"test","tags":["tag"]}]
```

**Comment by Haybu** [comment]
I am facing a typical error, any resolution?
