### ISSUE TITLE
Problem with exponents

### ISSUE THREAD

**Issue by franbanho** [json-path/JsonPath#590]
Hi,
there is an issue related to exponents that was found using **Jsonassert**. [issue Jsonassert](https://github.com/marcingrzejszczak/jsonassert/issues/31)

This happens to me using numbers of the form **1.12E-7** for example.

I think the problem happens when the method **com.toomuchcoding.jsonassert.JsonAsserter#numberValue** returns a String representation that still contains "E-7", but in case it can transform the number to 0.000000112 then it works fin, but instead if that method returns 1.12E-7 then I get the following stack trace:

`[ERROR] 2020-01-13 15:52:35.432 [main] JsonAsserter - Exception occurred while trying to match JSON Path [$[?(@.n == 1.12E-7)]]
com.jayway.jsonpath.InvalidPathException: Expected character: )
	at com.jayway.jsonpath.internal.CharacterIndex.readSignificantChar(CharacterIndex.java:218) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalANDOperand(FilterCompiler.java:185) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalAND(FilterCompiler.java:151) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalOR(FilterCompiler.java:131) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:77) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:53) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readFilterToken(PathCompiler.java:461) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:141) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:87) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:96) ~[json-path-2.4.0.jar:2.4.0]
	at com.toomuchcoding.jsonassert.JsonAsserter.parseJsonPathAsArray(JsonAsserter.java:259) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.jsonPathToArray(JsonAsserter.java:254) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.check(JsonAsserter.java:226) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.checkBufferedJsonPathString(JsonAsserter.java:267) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.isEqualTo(JsonAsserter.java:146) [jsonassert-0.4.13.jar:?]`

**Comment by Youngea** [comment]
Hi, I would like to look into the issue.

**Comment by kallestenflo** [comment]
Fixed by #718
