### ISSUE TITLE
json-path-2.x.x.jar conflicts with hadoop environment json-smart-1.x.jar

### ISSUE THREAD

**Issue by arr4it** [json-path/JsonPath#634]
hadoop project has a hard dependency on json-smart-1.x jar
we will be able to run json-path-0.x.x jars in hadoop (as it is dependent on json-smart-1.x version), but we were not able to use latest features like DocumentContext.
Incase if register explicitly **json-smart-2.x** jar in hadoop job still hadoop picksup **json-smart-1.x** version as it is a core dependency for hadoop job.
is there any possibility to allow hadoop users to use json-path 2.x version?
basically we want to use **json-path-2.x** version with **json-smart-1.x** version or without any dependency on json-smart.

Same issue for all hadoop users (below are couple of stackoverflow issues):
https://stackoverflow.com/questions/61530162/java-lang-nosuchfielderror-defaultreader-jsonsmartjsonprovider-java39
https://stackoverflow.com/questions/56945580/json-path-2-3-0-conflicts-with-hadoop-2-7-environment-json-smart1-2-0-jar

**Error in Hadoop:**
java.lang.NoSuchFieldError: defaultReader
at com.jayway.jsonpath.spi.json.JsonSmartJsonProvider.<init>(JsonSmartJsonProvider.java:39)
at com.jayway.jsonpath.internal.DefaultsImpl.jsonProvider(DefaultsImpl.java:21)
at com.jayway.jsonpath.Configuration.defaultConfiguration(Configuration.java:174)
at com.jayway.jsonpath.internal.JsonContext.<init>(JsonContext.java:52)
at com.jayway.jsonpath.JsonPath.parse(JsonPath.java:596)

We loved the project but unable to use, Please let us know if there is any solution for this problem.

Thanks in advance

**Comment by arr4it** [comment]
we can avoid json-smart dependency using the below default config change.    

public static void changeJsonPathConfig() {
            Configuration.setDefaults(new Configuration.Defaults() {

                private final JsonProvider jsonProvider = new GsonJsonProvider(
                        new GsonBuilder().serializeNulls().create());
                private final MappingProvider mappingProvider = new GsonMappingProvider();

                @Override
                public JsonProvider jsonProvider() {
                    return jsonProvider;
                }

                @Override
                public MappingProvider mappingProvider() {
                    return mappingProvider;
                }

                @Override
                public Set<Option> options() {
                    return EnumSet.noneOf(Option.class);
                }
            });

    }
