### ISSUE TITLE
make it quarkus compatible

### ISSUE THREAD

**Issue by ryckowski** [json-path/JsonPath#664]
If feasible it would be nice to have to make it compatible with quarkus https://quarkus.io/
Currently I'm getting errors while building into native
`Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain): 
    at java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:878)
    at net.minidev.asm.DynamicClassLoader.defineClass(DynamicClassLoader.java:86)
    at net.minidev.asm.BeansAccessBuilder.bulid(BeansAccessBuilder.java:313)
    at net.minidev.asm.BeansAccess.get(BeansAccess.java:111)
    at net.minidev.json.reader.BeansWriterASM.writeJSONString(BeansWriterASM.java:17)`
It happens only if I add json-path as dependency thus I'm assume it's about  json path and it tries to dynamically add some classes

**Comment by ryckowski** [comment]
Managed to solve it. Downgraded and used solution made in quarkus-camel-json-path
