### ISSUE TITLE
[version: 2.7.0] Json-smart provider does not support TypeRef! Use a Jackson or Gson based providerJson-smart provider does not support TypeRef! Use a Jackson or Gson based provider

### ISSUE THREAD

**Issue by shenngw1127** [json-path/JsonPath#802]
static method

```java
    public static <T> List<T> getJsonPathList2(String jsonString,
                                               String jsonPath,
                                               Class<T> tClass) {
        final ObjectMapper objectMapper2 = new ObjectMapper()
                .setPropertyNamingStrategy(PropertyNamingStrategy.UPPER_CAMEL_CASE)
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        final Configuration conf2 =
                Configuration.builder()
                        .jsonProvider(new JacksonJsonProvider(objectMapper2))
                        .options(Option.SUPPRESS_EXCEPTIONS)
                        .build();
        return JsonPath.using(conf2).parse(jsonString)
                .read(jsonPath, new TypeRef<List<T>>() {
                    @Override
                    public Type getType() {
                        return objectMapper2.getTypeFactory().constructParametricType(List.class,
                                tClass);
                    }
                });
    }
```

call static method

```java
    @Test
    void test() {
        List<DataModel> dataModelList = JsonPathUtils.getJsonPathList2("{\"Items\": []}",
                "Items", DataModel.class);
        log.debug("dataModelList: {}", dataModelList);
        assertEquals(0, dataModelList.size());
    }
```

error here

```txt
java.lang.UnsupportedOperationException: Json-smart provider does not support TypeRef! Use a Jackson or Gson based provider

	at com.jayway.jsonpath.spi.mapper.JsonSmartMappingProvider.map(JsonSmartMappingProvider.java:94)
	at com.jayway.jsonpath.internal.JsonContext.convert(JsonContext.java:121)
```

version: 2.6.0  or 2.7.0

**Comment by SingingBush** [comment]
I'm affected by this same bug in version 2.7.0, I'm clearly using the JacksonJsonProvider:

```java
final TypeRef<List<MyPojo>> typeReference = new TypeRef<>() {};

final List<MyPojo> argusMessages = JsonPath.using(
        Configuration.builder()
                .jsonProvider(new JacksonJsonProvider(new ObjectMapper()))
                .build()
    )
    .parse(responseJson)
    .read("$['aggregations']['my_agg']['buckets'][*]['latest']['hits']['hits'][0]['_source']", typeReference);
```

but it fails with the message:

```
java.lang.UnsupportedOperationException: Json-smart provider does not support TypeRef! Use a Jackson or Gson based provider

	at json.path@2.7.0/com.jayway.jsonpath.spi.mapper.JsonSmartMappingProvider.map(JsonSmartMappingProvider.java:94)
	at json.path@2.7.0/com.jayway.jsonpath.internal.JsonContext.convert(JsonContext.java:121)
	at json.path@2.7.0/com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:103)
```

**Comment by shenngw1127** [comment]
@SingingBush 

Thanks a lot!

add this line, i can use Jackson to deserialize the json.

``.mappingProvider(new JacksonMappingProvider(mapper))``
