### ISSUE TITLE
Mapping exception when parsing array of objects JSON

### ISSUE THREAD

**Issue by datoslabs** [json-path/JsonPath#896]
Hi,

I have a JSON array of objects with nested arrays of strings, e.g. 
```
[
	{
		"key1":"prop1",
		"key2":["prop2", "prop2a"],
		....
	},
	{
		"key1":"prop1a",
		"key2":["prop2", "prop2a"],
		....
	},...
]
```

When trying to parse it using `ReadContext` with `ArrayList<HashMap<String, Object>>` `TypeRef`, it throws an exception while parsing the nested array of strings as it appears that it's trying to map the array content (string) as objects (HashMap).  Following is a snippet of the exception:

```
com.jayway.jsonpath.spi.mapper.MappingException: java.lang.IllegalArgumentException: Cannot construct instance of `java.util.HashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('Added_As_Audience')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.util.ArrayList[25])
	at com.jayway.jsonpath.spi.mapper.JacksonMappingProvider.map(JacksonMappingProvider.java:58)
	at com.jayway.jsonpath.internal.JsonContext.convert(JsonContext.java:121)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:103)
	at test.JsonPathTest2.main(JsonPathTest2.java:158)
	...
```
where 'Added_As_Audience' string is the content of the nested array of strings.

However, when the above JSON array is wrapped inside a "shell" object as follows, the error disappeared:

```
{
	"elements": // JSON array from above //
}
```
Jackson version: 2.9.10
Jayway-Jsonpath version: 2.7.0
jdk 11

Full test code:

```
public class JsonPathTest {
	static final String JSON1 = "[{\r\n"
			+ "		\"id\": \"1\",\r\n"
			+ "		\"type\": \"startNode\",\r\n"
			+ "		\"data\": {\r\n"
			+ "			\"label\": \"Start\",\r\n"
			+ "			\"sourceHandle\": {\r\n"
			+ "				\"s-1-1\": {\r\n"
			+ "					\"offset\": \"50%\"\r\n"
			+ "				}\r\n"
			+ "			},\r\n"
			+ "			\"actions\": [{\r\n"
			+ "				\"engine\": \"mvel\",\r\n"
			+ "				\"expressions\": {\r\n"
			+ "					\"onStateExit\": \"System.out.println(\\\"[MVEL]\\tInside onStateExit action.\\\");\"\r\n"
			+ "				}\r\n"
			+ "			}]\r\n"
			+ "		},\r\n"
			+ "		\"position\": {\r\n"
			+ "			\"x\": 50,\r\n"
			+ "			\"y\": 50\r\n"
			+ "		}\r\n"
			+ "	},\r\n"
			+ "	{\r\n"
			+ "		\"id\": \"2\",\r\n"
			+ "		\"type\": \"stateNode\",\r\n"
			+ "		\"data\": {\r\n"
			+ "			\"label\": \"Not_Engaged\",\r\n"
			+ "			\"sourceHandle\": {\r\n"
			+ "				\"s-2-1\": {\r\n"
			+ "					\"offset\": \"50%\"\r\n"
			+ "				}\r\n"
			+ "			},\r\n"
			+ "			\"targetHandle\": {\r\n"
			+ "				\"t-2-1\": {\r\n"
			+ "					\"offset\": \"50%\"\r\n"
			+ "				}\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		\"position\": {\r\n"
			+ "			\"x\": 100,\r\n"
			+ "			\"y\": 100\r\n"
			+ "		}\r\n"
			+ "	},\r\n"
			+ "	{\r\n"
			+ "		\"id\": \"6\",\r\n"
			+ "		\"data\": {\r\n"
			+ "			\"label\": \"End\",\r\n"
			+ "			\"targetHandle\": {\r\n"
			+ "				\"t-6-1\": {\r\n"
			+ "					\"offset\": \"50%\"\r\n"
			+ "				},\r\n"
			+ "				\"t-6-2\": {\r\n"
			+ "					\"offset\": \"50%\"\r\n"
			+ "				}\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		\"position\": {\r\n"
			+ "			\"x\": 800,\r\n"
			+ "			\"y\": 300\r\n"
			+ "		},\r\n"
			+ "		\"type\": \"endNode\"\r\n"
			+ "	},\r\n"
			+ "	{\r\n"
			+ "		\"id\": \"e1-2\",\r\n"
			+ "		\"source\": \"1\",\r\n"
			+ "		\"sourceHandle\": \"s-1-1\",\r\n"
			+ "		\"target\": \"2\",\r\n"
			+ "		\"targetHandle\": \"t-2-1\",\r\n"
			+ "		\"label\": \"Added_As_Audience\",\r\n"
			+ "		\"data\": {\r\n"
			+ "			\"triggers\": [\r\n"
			+ "				\"Added_As_Audience\"\r\n"
			+ "			],\r\n"
			+ "			\"edgeType\": \"EXTERNAL_TRANSITION\",\r\n"
			+ "			\"salience\": 0,\r\n"
			+ "			\"actions\": [{\r\n"
			+ "				\"engine\": \"mvel\",\r\n"
			+ "				\"expressions\": {\r\n"
			+ "					\"after\": \"modelData.stepCount = 1\"\r\n"
			+ "				}\r\n"
			+ "			}],\r\n"
			+ "			\"guards\": {\r\n"
			+ "				\"when\": [{\r\n"
			+ "					\"engine\": \"mvel\",\r\n"
			+ "					\"expression\": \"System.out.println(\\\"[MVEL]\\tAdded_As_Audience-when transition guard.\\\"); return true;\"\r\n"
			+ "				}],\r\n"
			+ "				\"except\": [{\r\n"
			+ "					\"engine\": \"mvel\",\r\n"
			+ "					\"expression\": \"System.out.println(\\\"[MVEL]\\tAdded_As_Audience-except transition guard.\\\"); return false;\"\r\n"
			+ "				}]\r\n"
			+ "			}\r\n"
			+ "		},\r\n"
			+ "		\"type\": \"enhanced\",\r\n"
			+ "		\"arrowHeadType\": \"arrow\"\r\n"
			+ "	}\r\n"
			+ "]" ;
	
	static final String JSON2 = "{\"elements\":" + JSON1 + "}";

	public static final String EDGES_PATH1 = "$..[?(@.source || @.target)]";
	public static final String NODES_PATH1 = "$..[?(!@.source && !@.target)]";

	public static final String EDGES_PATH2 = "$.elements.[?(@.source || @.target)]";
	public static final String NODES_PATH2 = "$.elements.[?(!@.source && !@.target)]";
	static {
		Configuration.setDefaults(new Configuration.Defaults() {

			private final JsonProvider jsonProvider = new JacksonJsonProvider();
			private final MappingProvider mappingProvider = new JacksonMappingProvider();

			@Override
			public JsonProvider jsonProvider() {
				return jsonProvider;
			}

			@Override
			public MappingProvider mappingProvider() {
				return mappingProvider;
			}

			@Override
			public Set<Option> options() {
				return EnumSet.noneOf(Option.class);
			}
		});
	}

	public static void main(String[] args) throws IOException {

		InputStream testJson = Thread.currentThread().getContextClassLoader().getResource("SimpleStateMachine.json")
				.openStream();

		try {
			System.out.println("=========== Test1 =========== ");
			ReadContext ctx1 = JsonPath.parse(JSON1);
			ctx1.read(EDGES_PATH1, new TypeRef<ArrayList<HashMap<String, Object>>>() {
			});
			ctx1.read(NODES_PATH1, new TypeRef<ArrayList<HashMap<String, Object>>>() { //line 158
			}); 
			System.out.println("Test1 OK.");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			System.out.println("=========== Test2 =========== ");
			ReadContext ctx2 = JsonPath.parse(JSON2);
			ctx2.read(EDGES_PATH2, new TypeRef<ArrayList<HashMap<String, Object>>>() {
			});
			ctx2.read(NODES_PATH2, new TypeRef<ArrayList<HashMap<String, Object>>>() {
			});
			System.out.println("Test2 OK.");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
```

**Comment by mimajiushi** [comment]
+1, don' use JacksonJsonProvider, use `Configuration.defaultConfiguration()`, it will be right
