### ISSUE TITLE
The functions don't work in any JSON parsed afterwards.

### ISSUE THREAD

**Issue by andriy-samson** [json-path/JsonPath#938]
When the ReadContext instance is created more then once, the behavior of sum(), min(), max(), avg() and probably other functions is wrong.
Here's a code snippet to reproduce the problem:

```
ReadContext ctx = JsonPath.parse("{'arr': [1,2]}");
ctx.read("max($.arr[*])");    // OK: returns 2

ReadContext ctx2 = JsonPath.parse("{'arr': [3,4]}");
ctx2.read("max($.arr[*])");   // raise Error.
```

The call ctx2.read(...) raise an exception:

```
12:53:22.786 [main] DEBUG com.jayway.jsonpath.internal.path.CompiledPath - Evaluating path: $.max(...)
12:53:22.818 [main] DEBUG com.jayway.jsonpath.internal.path.CompiledPath - Evaluating path: $['arr'][*]
12:53:22.818 [main] DEBUG com.jayway.jsonpath.internal.path.CompiledPath - Evaluating path: $.max(...)
12:53:22.818 [main] DEBUG com.jayway.jsonpath.internal.path.CompiledPath - Evaluating path: $['arr']
Exception in thread "main" com.jayway.jsonpath.JsonPathException: Aggregation function attempted to calculate value using empty array
	at com.jayway.jsonpath.internal.function.numeric.AbstractAggregation.invoke(AbstractAggregation.java:59)
	at com.jayway.jsonpath.internal.path.FunctionPathToken.evaluate(FunctionPathToken.java:41)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:66)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:99)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:107)
	at com.jayway.jsonpath.JsonPath.read(JsonPath.java:179)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:88)
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:77)
	at com.objectiflune.tests.json.JsonFuncTest.main(JsonFuncTest.java:15)_


```
All functions work as expected, but only in the first json parsed. Once a new context is created, many functions throw the exception.
For this to work again, the application must be restarted.

It seems that there are cached variables linked to the process that cause incorrect parameter validation for the second context.

**Comment by andriy-samson** [comment]
After a little research, I found out more about this problem:

It seems that the problem is caused by the _FunctionPathToken.cleanWildcardPathToken()_ method. The wildcard path token is removed from the JsonPath function, causing a bad output for the cached JsonPath when it is called second time for the same JsonPath.

The issue was introduced as a bug fix for https://github.com/json-path/JsonPath/issues/786, so the problem has existed since March 2022.

For this problem, one of the following workarounds can help:

1. Avoid caching the JsonPath function in the default LRUCache.java file.
2. Use a custom cache instance that will not cache the JsonPath function.
